actionDim: 3
actionMin: [-1,-1,-1]
actionMax: [1, 1, 1]

steer:
        max_speed: 0.2

purePursuit:
        steer_scale: 0.75
        wheel_base: 0.75
        lookahead: 2.0
        throttle_pid: [1,0,0]
        max_error_sum: 1

RRT:
        speedRange: [0.05, 0.05]
        steerDist: 1.0
        rewireDist: 2.0
        p_goal: 0.1
        maxIterations: 200
        goalTol: 0.1
        numCollisionAttempts: 1
        steerLimit: 0.8
        thresh: 0.5
        lr: 0.01
        epochs: 150
        path_weight: 10
        div_weight: 1

divergence:
        scale: [1,1,0.25]
        thresh: 0.5
        num_particles: 32
        cvar: 1.0
