stateTransitionDim: 3
contextDim: 1

localMap:
        dim: [1.5,0.75]
        resolution: [32,16]

dynamicsModel:
        varLowBound: 0.001
        hidden_size: 256
        num_layers: 1
        dropout: 0
        maxTrajRefDist: 1.0
        staticVar: False
        ignoreContext: True
        terrain:
                in_channels: 1
                compressedDim: 8
                layer_channels: [16,32] #default:[64,128,256,512]
                layer_strides: [1,1] #default:[1,2,2,2]
                num_blocks: [1,1]

sysID:
        pooling_op: "global_mean"
        d_model: 128
        nhead: 8
        dim_feedforward: 64
        dropout: 0.0
        num_layers: 1
        max_seq_len: 3000
        terrain:
                in_channels: 1
                compressedDim: 8
                layer_channels: [8,16] #default:[64,128,256,512]
                layer_strides: [1,1] #default:[1,2,2,2]
                num_blocks: [1,1]
        stochastic: False

robot_param:
        fc_sizes: []
        fric_only: False
        stochastic: True
